### ISSUE TITLE
Bad SSL certificate

### ISSUE THREAD

**Issue by redsPL** [leopardslab/installer.to#28]
**Describe the bug**
```
$ curl https://installer.to/git | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4787    0  4787    0     0  13795      0 --:--:-- --:--:-- --:--:-- 13755
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'
```
After entering https://installer.to/git in a web browser, it appears that cloudflare errors out on a bad SSL certificate.

**To Reproduce**
1. Enter the webpage

**Expected behavior**
It should work

**Screenshots**
![why do you need a screenshot for that I don't know](http://f.sakamoto.pl/f2854226-dd83-46ae-9ce8-64d8bb679b24file_52.jpg)

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Smartphone (please complete the following information):**
 - Device: any 
 - OS: any
 - Browser: any
 - Version: any

**Additional context**
You should really revise this template, it's not helpful at all.

**Comment by tdevinda** [comment]
Looks like the site itself has gone kaboom for some reason. :(

**Comment by agentmilindu** [comment]
Fixed! :D
