### ISSUE TITLE
Proposal for `docker` to have a installer script

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/installer.to#5]
## How the "cURL & bash" command be

```
curl https://installer.to/docker | bash
```
## Checklist
- [x] I checked the Issues list and I'm sure I'm not duplicating an existing request
- [x] I checked the Pull Request list and I'm sure I'm not proposing for a tool that is about to get added

----

I request the community to consider my proposal and cast your votes by commenting,
* `+1` if you like to see an installer script for this tool in this repo
* `-1` if you do not like to see an installer script for this tool in this repo

**Comment by agentmilindu** [comment]
We can use https://get.docker.com script for this.

**Comment by lakinduakash** [comment]
Won't work same script without changes from [get.docker.com](https://get.docker.com)?

**Comment by agentmilindu** [comment]
@lakinduakash  https://get.docker.com is their official script. we can reuse it, they might be updating it, we need to get the updates also.
