### ISSUE TITLE
Need a simple web page for informational purposes

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/installer.to#7]
We need a very simple web page as the app front, with some info about the app. Need a good UX design and a simple implementation. This site should be able to give the whole idea of the app in a single glance.

**Comment by harsha-iiiv** [comment]
Can I work on this?

**Comment by asithc** [comment]
#8 
 Hi, @agentmilindu I did some work for this.
https://github.com/asithc/installer.to/tree/master/public/App%20web-template%20-Intaller.to

**Comment by agentmilindu** [comment]
@asithc Go ahead, create PR. Also, add some screenshots to the PR description ;)
